name: Playwright Tests

on:
  push:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      PASSWORD: ${{ secrets.SECRET_KEY }}   # Available to all steps
      SMTH: "SOMETHING..."
    container:
      image: mcr.microsoft.com/playwright:v1.54.0-noble
    steps:
      - name: Debug secret and env
        run: |
          echo "This is the PASSWORD env var: $PASSWORD"
          echo "Custom variable: $SMTH"
        shell: bash

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
