name: Scheduled Cron Job workflow in Docker container
on:
  schedule:
    - cron: '0 3 * * *'  # Runs every day at 3:00 AM UTC
jobs:
  playwright-scheduled-job:
    name: 'Playwright Tests Docker'
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      PASSWORD: ${{ secrets.SECRET_KEY }}
      SMTH: "This is a values defined in the workflow"
    container:
      image: mcr.microsoft.com/playwright:v1.54.0-noble
    steps:
      - name: Debug secret presence
        run:
          echo "SECRET KEY = $PASSWORD"
          echo "Workflow defined var SMTH = $SMTH"
          echo "Length of PASSWORD is:" ${#PASSWORD}
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Say Hello
        run: echo "Hello! This job runs on a schedule in a Docker container."
      - name: Install dependencies
        run: npm ci
      - name: Run your tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
